// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebsiteLomba.Data;

#nullable disable

namespace WebsiteLomba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250708112819_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebsiteLomba.Models.Lomba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kontak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkPendaftaran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaLomba")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Lombas");
                });
#pragma warning restore 612, 618
        }
    }
}
