// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebsiteLomba.Data;

#nullable disable

namespace WebsiteLomba.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebsiteLomba.Models.Lomba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Deskripsi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GambarPath")
                        .HasColumnType("text");

                    b.Property<string>("Kontak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LinkPendaftaran")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NamaLomba")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalMulai")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TanggalSelesai")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Lombas");
                });

            modelBuilder.Entity("WebsiteLomba.Models.Peserta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LombaId")
                        .HasColumnType("integer");

                    b.Property<string>("NamaPeserta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomorTelepon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalDaftar")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LombaId");

                    b.ToTable("Pesertas");
                });

            modelBuilder.Entity("WebsiteLomba.Models.Peserta", b =>
                {
                    b.HasOne("WebsiteLomba.Models.Lomba", "Lomba")
                        .WithMany()
                        .HasForeignKey("LombaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lomba");
                });
#pragma warning restore 612, 618
        }
    }
}
